# Generated by Django 2.0.6 on 2018-06-13 08:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heroes', wagtail.core.blocks.static_block.StaticBlock(admin_text='Heroes block: no configuration needed.', template='heroes.html')), ('index', wagtail.core.blocks.RichTextBlock()), ('text_plus_screenshot', wagtail.core.blocks.StreamBlock([('screenshot', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock())], template='text_plus_screenshot.html'))], default=''),
            preserve_default=False,
        ),
    ]
