# Generated by Django 2.0.6 on 2018-06-13 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='PromoPage',
        ),
    ]
